spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpatest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    org.hibernate.sql: debug
